## Linear Algebra Quiz #3

![title](./img/3_0.jpeg)

We strongly suggest working with numpy :)

In [1]:
#Do your imports here
import numpy as np

![title](./img/3_2.png)
![title](./img/3_3.png)
Create a program that can output

- What is the value of element c23​ of Matrix C where C=A x B ?
- What is the value of element c23​ of Matrix C where C=B x A ?

In [38]:
A = np.array([[3,1,2],[-5,4,1],[0,3,-8]])
B = np.array([[0,5,-1],[3,2,-1],[10,0.5,4]])
C = np.matmul(A, B)
C


array([[ 23. ,  18. ,   4. ],
       [ 22. , -16.5,   5. ],
       [-71. ,   2. , -35. ]])

In [42]:
# When C = A x B,
# C[1][2] = 5.0
# When C = B x A
C = np.matmul(B, A)
C
# C[1][2] = 16.0

array([[-25. ,  17. ,  13. ],
       [ -1. ,   8. ,  16. ],
       [ 27.5,  24. , -11.5]])

In [56]:
# okay numpy is great but... how would you inverse a matrix by hand?
def inverse_matrix(A):
    return np.linalg.inv(A)

inverse_matrix([[1,-10,11],[4,10,5], [4,6,9]])   

array([[ 1.36363636,  3.54545455, -3.63636364],
       [-0.36363636, -0.79545455,  0.88636364],
       [-0.36363636, -1.04545455,  1.13636364]])

![title](./img/3_1.png)
Create a program that can output

- What is the value of the ijth element if i = 2 and j=3?
- What is the value of the ijth element if i = 3 and j=1?

In [8]:
A = np.array([[3, 0.6, 4, -3],[-1.3,4,0,8.6],[7,0,-8,0.006]])
B = np.array([[3, -5.76, 45, 0],[2, -2, 1.3 , 9],[-9, 0,0,0]])
C = np.array([[0,1009, -66.7849, 90],[0,5,4,-0.07],[-7.7,0,0,0]])
D = A + B - C
#D[1][2] = -2.7
#D[2][0] = 5.7

-2.7

In [ ]:
# Just answer using code --> easy stuff!

# Harder
# Can you build a matrix solver that can do output the result given n matrices and a sequence of operations such as [add subtract multiply transpose?]
#Some ideas on valid operations: Multiplication Addition Subtraction Inverstion Transposed. 

![title](./img/3_3.png)
Create a program that can output
- How many rows will C have?
- How many columns will C have?
- What will be the value of c13​?

In [9]:
A = np.array([0.6,-15,2,5,98])
B = np.array([[2,2,-4],[9,-14,0],[13,-0.5,44],[1,9,4],[0,0,5]])

In [11]:
C = np.matmul(A.T, B)

In [12]:
C

array([-102.8,  255.2,  595.6])

In [ ]:
# C will have one rows 
# C will have zero columns
# The value of C13 = 595.6  i.e C[2]