## Remember that the solutions need to be saved int variable provided.

In [198]:
# Import the needed libraries
import numpy as np

**13. Create a 10x10 array with random values and find the minimum and maximum values**

In [199]:
# 1 point
# YOUR CODE HERE
sol1 = np.random.randint(100, size=(10,10))
print(sol1)
print("Max: ",np.amax(sol1))
print("Min: ",np.amin(sol1))

[[49 88 24 45  2 87  5 22 11 82]
 [43 48 73 91  1 50 78 39 35 80]
 [31 84 68 37 31 79 90 40 70 14]
 [21  0 98 79  2 94 84 38 72 35]
 [83  8 11  9 65 74 38 35 73 91]
 [45 63 86 30 75 91 19 23 14 79]
 [67  9 73 89 71 85 32 81 96 48]
 [96 65  1 67 80 52 82 56 92 58]
 [77 33 78 85 56 33 45 42 85 52]
 [59  8 20 83 79 43 61 84 57  8]]
Max:  98
Min:  0


In [200]:
assert sol1.shape == (10,10)

**15. Create a 2d 10x10 array with 1 on the border and 0 inside**

In [201]:
#1 points
sol2 = np.zeros((10,10), dtype='i')
#print(my_array)
sol2[:,0] = 1
sol2[:,-1] = 1
sol2[0,:] = 1
sol2[-1,:] = 1
print(sol2)
# YOUR CODE HERE

[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [202]:
assert sol2.shape == (10,10)
assert sol2[0].all() == 1
assert sol2[:,0].all() == 1
assert sol2[1][1] == 0
assert sol2[2][2] == 0
assert sol2[3][3] == 0
assert sol2[4][4] == 0
assert sol2[1][2] == 0
assert sol2[2][3] == 0
assert sol2[3][4] == 0
assert sol2[4][5] == 0

**34. How to get all the dates corresponding to the month of July 2016**

In [210]:
#2 points
sol3 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(sol3)
# YOUR CODE HERE
#print(sol3)
#print(sol3[0].dtype)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [207]:
assert sol3.shape == (31,)
assert type(sol3[0]) is np.datetime64

AssertionError: 

**42. Consider two random arrays based on the normal and uniform distributions 10x10 sol41 and sol42, check if they are equal**

In [181]:
# Testing Code
arr1 = np.array([1,2,3])
arr2 = np.array((1,5,6))

for index in range(len(arr1)):
    if arr1[index] == arr2[index]:
        print(arr1[index]==arr2[index])

True


In [192]:
#2 points
sol41 = np.random.normal(size=(10,10))
sol42 = np.random.uniform(size=(10,10))
comparisson = (sol42==sol41)
#print(comparisson)
# YOUR CODE HERE

In [193]:
bol = True

for l in comparisson:
    for c in l:
        if c:
            bol = False


assert bol

**72. How to swap two rows of an array?** 

In [194]:
#3 points
sol5 = np.array([[1,2,3],[4,5,6]])

# YOUR CODE HERE
#print(sol5)
sol5[[0, 1]] = sol5[[1, 0]]
sol5

array([[4, 5, 6],
       [1, 2, 3]])

In [195]:
assert sol5[0][0] == 4
assert sol5[0][1] == 5
assert sol5[0][2] == 6

assert sol5[1][0] == 1
assert sol5[1][1] == 2
assert sol5[1][2] == 3


**75. How to compute averages using a sliding window over an array?**

In [196]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
# YOUR CODE HERE
lists = []
total = 0
for i in range(len(arr)):
    total+=arr[i:i+1]
    average = total/len(arr)
    lists.append(average)
    
reshape_array = np.array(lists).reshape(1,10)
reshape_array

array([[0.1, 0.3, 0.6, 1. , 1.5, 2.1, 2.8, 3.6, 4.5, 5.5]])

In [197]:
assert sol6[-1] == 5.5
assert sol6[0] == 0.1
assert sol6[4] == 1.5